import {randomUUID} from 'node:crypto';
import {type ResearchResult,type Proposal,AppError} from '../shared/contracts';
export function createPreview(rejectedIds:string[]=[]):ResearchResult{
  const evidenceId='illustrative-evidence';
  const places=[
    {id:'preview-paper-moon',name:'Paper Moon Coffee',type:'Coffee & conversation',address:'Illustrative location in Austin',description:'An intimate coffee counter with a listening corner. A natural setting for a small reading and record exchange.'},
    {id:'preview-soft-sound',name:'Soft Sound Café',type:'Coffee & listening',address:'Illustrative location in Austin',description:'A neighborhood café concept built around listening sessions and independent artists.'},
    {id:'preview-sunday',name:'Sunday House',type:'Coffee & gatherings',address:'Illustrative location in Austin',description:'A small café concept for slow Sundays, thoughtful conversations, and creative workshops.'},
    {id:'preview-common-table',name:'The Common Table',type:'Food & community',address:'Illustrative location in Austin',description:'A shared-table café concept that could pair a seasonal menu with an intimate author conversation.'}
  ];
  return {id:randomUUID(),mode:'preview',brief:{city:'Austin, Texas',category:'cafe',objective:'Bring new people into our independent bookstore with a thoughtful, small-format neighborhood event.',references:[{id:'preview-murakami',name:'Haruki Murakami',type:'author'},{id:'preview-khruangbin',name:'Khruangbin',type:'artist'},{id:'preview-before-sunrise',name:'Before Sunrise',type:'movie'}],rejectedIds},candidates:places.filter(p=>!rejectedIds.includes(p.id)).map((p,i)=>({...p,providerRank:i+1,evidenceIds:[evidenceId],explanation:null})),evidence:[{id:evidenceId,source:'Illustrative',operation:'product walkthrough',fetchedAt:new Date().toISOString(),request:{city:'Austin',example:true},entityIds:places.map(p=>p.id),metrics:{},details:'All businesses and recommendations in this walkthrough are fictional. No Qloo request or model call was made.',limitations:['Illustrative examples, not Qloo results.','No measured affinity, customer overlap, location verification, or partner availability.']}],warnings:['Example mode: fictional businesses and editorial suggestions. Live Qloo research is a separate action.'],events:[{action:'Example brief loaded',detail:'A fictional independent bookstore in Austin. Three cultural references help define its intended audience.',status:'complete',timestamp:new Date().toISOString()},{action:'Illustrative shortlist',detail:'Four fictional partners show how discovery, evidence, revision, and proposal export work.',status:'complete',timestamp:new Date().toISOString()}],durationMs:0};
}
export function previewProposal(run:ResearchResult,id:string):Proposal{
  const candidate=run.candidates.find(c=>c.id===id);if(!candidate)throw new AppError('UNKNOWN_CANDIDATE','Choose a partner from this example.',400);
  return {title:'A good book. A new neighbor.',concept:`A proposed reading and listening evening bringing the bookstore together with ${candidate.name}. Invite guests to bring one passage and one song that belong together. This is an editorial example, not a verified recommendation.`,valueHypothesis:'A small shared event could introduce each business to people who enjoy related cultural experiences. Test this hypothesis through voluntary attendee feedback.',agenda:['Welcome guests and introduce both neighborhood businesses.','Pair short readings with a small selection of music, subject to permission and venue requirements.','Leave time for conversation and browsing; offer an optional feedback card.'],verificationQuestions:['Is the partner interested in the concept?','What capacity, accessibility needs, permissions and operating costs apply?','How will each business invite guests without sharing customer data?'],measurementPlan:'Record attendance, ask how guests heard about the event, and gather voluntary feedback on whether they would visit each business again. Do not infer sales lift from attendance alone.',evidenceIds:candidate.evidenceIds,candidate,mode:'preview',evidence:run.evidence,brief:run.brief};
}
