import {useState} from 'react';
import {ArrowUpRight,ArrowRight,MapPin,Check,ChevronDown,ChevronUp,Layers,X,LoaderCircle,BookOpen,Coffee,Music2,Info} from 'lucide-react';
import {type ResearchResult,type Candidate} from '../../shared/contracts';
function Neighborhood(){return <div className="neighborhood" aria-hidden="true"><div className="store store-book"><div className="store-roof"/><span>Books & stories</span><div className="store-front"><i/><i/><i/><i/><i/></div><div className="door"/></div><div className="connection"><span>+</span><i/></div><div className="store store-coffee"><div className="store-roof"/><span>Coffee & company</span><div className="coffee-window"><Coffee size={35} strokeWidth={1}/></div><div className="door"/></div><div className="ground-line"/><span className="neighborhood-caption">A little shared taste goes a long way.</span></div>;}
export function ResearchView({result,busy,onChoose,onReject,onExample,onCancel}:{result:ResearchResult|null;busy:boolean;onChoose:(candidate:Candidate)=>void;onReject:(candidate:Candidate)=>void;onExample:()=>void;onCancel:()=>void}){
  const [openEvidence,setOpenEvidence]=useState<string|null>(null),[showActivity,setShowActivity]=useState(false),[compared,setCompared]=useState<string[]>([]);
  const comparisons=result?.candidates.filter(c=>compared.includes(c.id))??[];
  if(busy)return <section className="results-panel busy-panel" aria-live="polite"><div className="research-orbit"><LoaderCircle size={35} className="spin" strokeWidth={1}/></div><h2>Making the connections.</h2><p>Resolving cultural evidence and checking your collaboration brief. Results will appear when the research is ready.</p><button className="secondary-button" onClick={onCancel}>Cancel research</button></section>;
  if(!result)return <section className="results-panel empty-panel"><div className="empty-kicker"><span className="dot"/> A new kind of local discovery</div><Neighborhood/><h2>Good neighbors.<br/>Better together.</h2><p>Your next collaboration might be a few streets away. Start with your audience’s cultural world, then discover who belongs in it.</p><button className="secondary-button" onClick={onExample}>Take a look around <ArrowUpRight size={17}/></button><div className="empty-features"><span><BookOpen size={17}/>Start with taste</span><span><Layers size={17}/>Follow the evidence</span><span><Coffee size={17}/>Make a plan</span></div></section>;
  return <section className="results-panel populated-panel" aria-label="Partner shortlist">
    <div className="results-heading"><div><div className="result-location"><MapPin size={14}/>{result.brief.city} & nearby</div><h2>Meet your possible partners.</h2></div><span className={`mode-badge ${result.mode}`}>{result.mode==='preview'?'Illustrative example':'Live Qloo research'}</span></div>
    <p className="results-intro">{result.mode==='preview'?'These fictional businesses show what a collaboration could look like. No measured affinity is implied.':'Your cultural references informed this shortlist. Compare the evidence, then choose a conversation to start.'}</p>
    {result.warnings.map((warning,i)=><div className="notice" key={i}><Info size={15}/><span>{warning}</span></div>)}
    {result.candidates.length===0&&<div className="no-results"><h3>No partners in this shortlist.</h3><p>Try another category or broaden your area explicitly in the brief.</p></div>}
    <div className="candidate-list">{result.candidates.map((candidate,i)=><article className="candidate" key={candidate.id}><div className={`candidate-art art-${i%4}`} aria-hidden="true">{i%3===0?<Coffee size={34} strokeWidth={1}/>:i%3===1?<Music2 size={34} strokeWidth={1}/>:<BookOpen size={34} strokeWidth={1}/>}<span>{candidate.name.split(' ').slice(0,2).join(' ')}</span></div><div className="candidate-main"><div className="candidate-top"><span className="candidate-category">{candidate.type.replace('urn:entity:','')}</span><button className="icon-button dismiss" title="Exclude this partner" aria-label={`Exclude ${candidate.name}`} onClick={()=>onReject(candidate)}><X size={15}/></button></div><h3>{candidate.name}</h3><p>{candidate.description}</p><div className="candidate-meta"><MapPin size={12}/>{candidate.address}</div><div className="candidate-actions"><button className="text-button evidence-button" onClick={()=>setOpenEvidence(openEvidence===candidate.id?null:candidate.id)}><Layers size={14}/>View evidence {openEvidence===candidate.id?<ChevronUp size={13}/>:<ChevronDown size={13}/>}</button><label className="compare-check"><input type="checkbox" checked={compared.includes(candidate.id)} onChange={e=>setCompared(e.target.checked?[...compared,candidate.id]:compared.filter(id=>id!==candidate.id))}/>Compare</label><button className="choose-button" onClick={()=>onChoose(candidate)}>Make a plan <ArrowUpRight size={15}/></button></div></div>{openEvidence===candidate.id&&<div className="evidence-detail"><h4>{result.mode==='preview'?'Example evidence record':'Source evidence'}</h4><p>{result.mode==='preview'?'These businesses and suggestions are fictional. This example illustrates the workflow, not Qloo performance.':'Qloo returned this candidate from the selected references and geographic filter. Its ordering is preserved from the discovery response.'}</p>{candidate.affinity!==undefined&&<p><strong>Provider affinity:</strong> {candidate.affinity} <span className="muted">(raw metric, not a success probability)</span></p>}{candidate.explanation!==null&&<details><summary>Input contribution details</summary><pre>{JSON.stringify(candidate.explanation,null,2)}</pre></details>}{result.evidence.filter(e=>candidate.evidenceIds.includes(e.id)).map(e=><details key={e.id}><summary>{e.source}: {e.operation}</summary><pre>{JSON.stringify(e,null,2)}</pre></details>)}</div>}</article>)}</div>
    {comparisons.length>0&&<div className="comparison"><div className="comparison-heading"><h3>Side by side</h3><button className="text-button" onClick={()=>setCompared([])}>Clear</button></div><div className="table-scroll"><table><thead><tr><th>Partner</th><th>Discovery order</th><th>Provider affinity</th><th>Evidence</th></tr></thead><tbody>{comparisons.map(c=><tr key={c.id}><th>{c.name}</th><td>{result.mode==='preview'?'Illustrative':c.providerRank}</td><td>{c.affinity??'Not supplied'}</td><td>{result.mode==='preview'?'Illustrative':`${c.evidenceIds.length} records`}</td></tr>)}</tbody></table></div></div>}
    <button className="activity-toggle" onClick={()=>setShowActivity(!showActivity)}><span><Check size={16}/>{result.mode==='preview'?'Walkthrough activity':'Research activity'} <small>{result.events.length} steps</small></span>{showActivity?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</button>{showActivity&&<ol className="activity-list">{result.events.map((event,i)=><li key={i}><span className="activity-dot"/><div><strong>{event.action}</strong><p>{event.detail}</p></div></li>)}</ol>}
    {result.brief.rejectedIds.length>0&&<p className="revision-note"><ArrowRight size={14}/>{result.brief.rejectedIds.length} excluded partner(s). The shortlist reflects your choice.</p>}
  </section>;
}
