import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Plus,X,Info,ArrowLeft} from 'lucide-react';
import {type Brief,type ResearchResult,type Candidate,type Proposal} from '../shared/contracts';
import {BriefEditor,freshBrief} from './components/BriefEditor';
import {ResearchView} from './components/ResearchView';
import {ProposalView} from './components/ProposalView';
import {api} from './api';
import {RequestGate} from './request-gate';
export function App(){
  const [brief,setBrief]=useState<Brief>(freshBrief),[result,setResult]=useState<ResearchResult|null>(null),[proposal,setProposal]=useState<Proposal|null>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[liveReady,setLiveReady]=useState(false),[showHelp,setShowHelp]=useState(false),[tag,setTag]=useState('');
  const gate=useRef(new RequestGate());
  useEffect(()=>{void api.status().then(s=>setLiveReady(s.liveReady)).catch(()=>{});return()=>gate.current.cancel();},[]);
  async function example(excluded:string[]=[]){const job=gate.current.begin();setBusy(true);setError('');setProposal(null);try{const run=await api.preview(excluded,job.signal);if(gate.current.current(job.id)){setBrief(run.brief);setResult(run);}}catch(e){if(gate.current.current(job.id))setError((e as Error).message);}finally{if(gate.current.current(job.id))setBusy(false);}}
  async function research(categoryTag:string,nextBrief=brief){const job=gate.current.begin();setBusy(true);setError('');setProposal(null);setTag(categoryTag);try{const run=await api.research(nextBrief,categoryTag,job.signal);if(gate.current.current(job.id)){setResult(run);setBrief(run.brief);}}catch(e){if(gate.current.current(job.id))setError((e as Error).message);}finally{if(gate.current.current(job.id))setBusy(false);}}
  async function choose(candidate:Candidate){if(!result)return;const job=gate.current.begin();setBusy(true);setError('');try{const p=await api.proposal(result.id,candidate.id,job.signal);if(gate.current.current(job.id)){setProposal(p);window.scrollTo({top:0});}}catch(e){if(gate.current.current(job.id))setError((e as Error).message);}finally{if(gate.current.current(job.id))setBusy(false);}}
  function reject(candidate:Candidate){if(!result)return;const excluded=[...new Set([...result.brief.rejectedIds,candidate.id])];if(result.mode==='preview')void example(excluded);else void research(tag,{...result.brief,rejectedIds:excluded});}
  function reset(){gate.current.cancel();setBusy(false);setResult(null);setProposal(null);setError('');setBrief(freshBrief());setTag('');}
  function editBrief(next:Brief){gate.current.cancel();setBusy(false);setBrief(next);setResult(null);setProposal(null);setError('');}
  return <><a className="skip-link" href="#workspace">Skip to workspace</a><header className="site-header no-print"><a href="/" className="wordmark" aria-label="Sidecar home"><span className="brand-symbol"><i/><i/></span>sidecar<span className="brand-period">.</span></a><nav aria-label="Main navigation"><a href="#workspace" className="active">Workspace</a><button onClick={()=>setShowHelp(true)}>How it works <ArrowUpRight size={13}/></button></nav><div className="header-status"><span className={`status-dot ${liveReady?'ready':''}`}/>{liveReady?'Live research configured':'Preview available'}</div></header>
    {showHelp&&<div className="help-panel no-print" role="region" aria-label="How Sidecar works"><button className="icon-button" aria-label="Close explanation" onClick={()=>setShowHelp(false)}><X size={18}/></button><h2>From shared taste to a shared idea.</h2><p>Choose cultural references that represent your business. Sidecar resolves them with Qloo, searches nearby partners, and lets you inspect the supporting evidence. Choose a partner to create a collaboration brief.</p><p>Qloo measures aggregate cultural relationships. It does not prove that your customers overlap or that a partner is available. The example walkthrough uses fictional businesses.</p></div>}
    <main id="workspace">{!proposal&&<div className="page-intro no-print"><div><div className="intro-label"><span className="tiny-link"/>A little local chemistry</div><h1>Find your next<br/>neighborhood collaboration.</h1></div><div className="intro-note"><p>For independent businesses<br/>with something in common.</p><span>Built with Qloo cultural intelligence <ArrowUpRight size={14}/></span></div></div>}
      {error&&<div className="global-error no-print" role="alert"><Info size={18}/><span>{error}</span><button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
      {proposal?<ProposalView proposal={proposal} onBack={()=>setProposal(null)} onChange={setProposal}/>:<><div className="workspace-title"><div><span className="workspace-dot"/>Collaboration workspace</div><button className="text-button" onClick={reset}><Plus size={15}/>{result?.mode==='preview'?'Start your own brief':'New brief'}</button></div><div className="workspace-grid"><BriefEditor brief={brief} setBrief={editBrief} busy={busy} preview={result?.mode==='preview'} onResearch={t=>void research(t)} onExample={()=>void example()}/><ResearchView result={result} busy={busy} onChoose={c=>void choose(c)} onReject={reject} onExample={()=>void example()} onCancel={()=>{gate.current.cancel();setBusy(false);}}/></div></>}
    </main><footer className="site-footer no-print"><span>Small businesses. Shared possibilities.</span><span>Cultural evidence, human decisions.</span><a href="https://qloo.devpost.com/" target="_blank" rel="noreferrer">Qloo Agentic Hackathon <ArrowUpRight size={12}/></a></footer></>;
}
